# need 4 gpus

project: coconut
entity: anirudhb11 #wandb entity
save_path: /network/scratch/b/buvanesa/coconut/graph_task
name: deg-5-path-len-5-num-nodes-300

only_eval: False

coconut: True
cot: False
no_thoughts: False
no_cot: False

c_thought: 1
epochs_per_stage: 5
max_latent_stage: 6
pad_latent_to_max: True

save_only_improve: False
uniform_prob: 0.0
model_id: openai-community/gpt2
load_model_path: None
seed: 0
resume: 0
bf16: False
train_path: data/star-graph-deg-5-path-5-nodes-300_train.json
val_path: data/star-graph-deg-5-path-5-nodes-300_valid.json
reset_optimizer: True
batch_size_training: 32
debug: False
gradient_accumulation_steps: 4
num_epochs: 50
lr: !!float "1e-4"
weight_decay: 0.01